<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114201319 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ref VARCHAR(50) NOT NULL, name VARCHAR(50) DEFAULT NULL, purchase_price NUMERIC(15, 2) NOT NULL, selling_price NUMERIC(15, 2) NOT NULL, created_at DATE NOT NULL, id_category INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD5697F554 ON product (id_category)');
        $this->addSql('CREATE TABLE product_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CDFC73565E237E06 ON product_category (name)');
        $this->addSql('CREATE TABLE product_stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT DEFAULT NULL, id_product INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA6A2D3CDD7ADDD ON product_stock (id_product)');
        $this->addSql('CREATE TABLE product_update (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ref VARCHAR(50) DEFAULT NULL, name VARCHAR(50) DEFAULT NULL, purchase_price NUMERIC(15, 2) DEFAULT NULL, selling_price NUMERIC(15, 2) DEFAULT NULL, update_at DATE NOT NULL, id_product INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FA5974DCDD7ADDD ON product_update (id_product)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, login VARCHAR(50) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, created_at DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9AA08CB10 ON users (login)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD5697F554 FOREIGN KEY (id_category) REFERENCES product_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_stock ADD CONSTRAINT FK_EA6A2D3CDD7ADDD FOREIGN KEY (id_product) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_update ADD CONSTRAINT FK_FA5974DCDD7ADDD FOREIGN KEY (id_product) REFERENCES product (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD5697F554');
        $this->addSql('ALTER TABLE product_stock DROP CONSTRAINT FK_EA6A2D3CDD7ADDD');
        $this->addSql('ALTER TABLE product_update DROP CONSTRAINT FK_FA5974DCDD7ADDD');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_category');
        $this->addSql('DROP TABLE product_stock');
        $this->addSql('DROP TABLE product_update');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
